version: '2'
services:

  backend:
    image: madina-tic/backend:0.1
    volumes:
      - migrations:/opt/backend/api/migrations
      - static_volume:/opt/backend/static
      - media_volume:/opt/backend/media
      - ./backups:/opt/backend/backups
    networks:
      - backend
      - backend_postgres
    ports:
      - 8000:8000
    depends_on:
      - "postgres"
    restart: on-failure
    environment:
      - PG_HOSTNAME=postgres
      - DJANGO_SETTINGS_MODULE=backend.settings
      
  frontend:
    image: madina-tic/frontend:0.2
    volumes:
      - MADINA-TIC-FRONT:/opt/frontend
    links:
      - nginx
    networks:
      - backend
    ports:
      - 5000:5000
    depends_on:
      - backend
    restart: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/backend/static
      - media_volume:/opt/backend/media
      - MADINA-TIC-FRONT:/opt/frontend
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    depends_on:
      - backend
    networks:
      - backend
    restart: on-failure
      
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: madina-tic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend_postgres
    restart: on-failure

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

volumes:
  migrations:
  pgdata:
  static_volume:
  media_volume:
  MADINA-TIC-FRONT:  

networks:
  backend:
  backend_postgres:
